use anyhow::{Context, Result};
use serde::Deserialize;
use std::process::Command;
use std::thread;
use std::time::Duration;

use crate::profile::{LidSwitch, Monitor, Position, Profile, Workspace};

/// Get the Hyprland instance signature, with fallback discovery
/// Usually set in the environment, but we can discover it if needed
fn get_hyprland_instance_signature() -> Option<String> {
    // First check if it's already set
    if let Ok(sig) = std::env::var("HYPRLAND_INSTANCE_SIGNATURE") {
        return Some(sig);
    }

    // Try to discover from XDG_RUNTIME_DIR/hypr/
    let runtime_dir = std::env::var("XDG_RUNTIME_DIR").ok()?;
    let hypr_dir = std::path::Path::new(&runtime_dir).join("hypr");

    if let Ok(entries) = std::fs::read_dir(&hypr_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            // Instance signatures look like: 386376400119dd46a767c9f8c8791fd22c7b6e61_1766260165_608814011
            if name_str.contains('_') && entry.path().is_dir() {
                return Some(name_str.to_string());
            }
        }
    }

    None
}

/// Create a hyprctl Command with the instance signature set
fn hyprctl_command() -> Command {
    let mut cmd = Command::new("hyprctl");
    if let Some(sig) = get_hyprland_instance_signature() {
        cmd.env("HYPRLAND_INSTANCE_SIGNATURE", sig);
    }
    cmd
}

// Timing constants for runtime apply
const MONITOR_APPLY_DELAY_MS: u64 = 1000;
const WORKSPACE_MOVE_RETRY_DELAY_MS: u64 = 500;
const WORKSPACE_MOVE_MAX_RETRIES: u8 = 3;

/// Raw monitor info from hyprctl monitors -j
#[derive(Debug, Deserialize)]
struct HyprMonitor {
    name: String,
    description: String,
    width: i32,
    height: i32,
    #[serde(rename = "refreshRate")]
    refresh_rate: f64,
    x: i32,
    y: i32,
    scale: f64,
    transform: u8,
}

/// Check if Hyprland is currently running
pub fn is_running() -> bool {
    Command::new("pgrep")
        .args(["-x", "Hyprland"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Detect currently connected monitors using hyprctl
pub fn detect_monitors() -> Result<Vec<Monitor>> {
    let output = hyprctl_command()
        .args(["monitors", "-j"])
        .output()
        .context("Failed to run hyprctl monitors")?;

    if !output.status.success() {
        anyhow::bail!("hyprctl monitors failed");
    }

    let hypr_monitors: Vec<HyprMonitor> = serde_json::from_slice(&output.stdout)
        .context("Failed to parse hyprctl output")?;

    let monitors = hypr_monitors
        .into_iter()
        .map(|m| {
            let resolution = format!("{}x{}", m.width, m.height);
            let mode = format!("{}x{}@{:.0}", m.width, m.height, m.refresh_rate);
            Monitor {
                name: m.name,
                description: Some(m.description),
                enabled: true,
                resolution,
                refresh_rate: m.refresh_rate,
                position: Position { x: m.x, y: m.y },
                scale: m.scale,
                transform: m.transform,
                mode,
            }
        })
        .collect();

    Ok(monitors)
}

/// Resolve stored monitor descriptions to current port names
/// This allows profiles to work even when dock assigns different port names
pub fn resolve_monitor_names(profile: &mut Profile) -> Result<()> {
    // Get current monitors from Hyprland
    let current_monitors = detect_monitors()?;

    for monitor in &mut profile.monitors {
        if let Some(ref desc) = monitor.description {
            // Find current monitor with matching description
            if let Some(current) = current_monitors.iter().find(|m| {
                m.description.as_ref() == Some(desc)
            }) {
                let old_name = std::mem::replace(&mut monitor.name, current.name.clone());

                // Update workspace references
                for ws in &mut profile.workspaces {
                    if ws.monitor == old_name {
                        ws.monitor = current.name.clone();
                    }
                }

                // Update lid_switch reference
                if let Some(ref mut lid) = profile.lid_switch {
                    if lid.monitor == old_name {
                        lid.monitor = current.name.clone();
                    }
                }
            }
        }
    }

    Ok(())
}

/// Generate Hyprland Lua config content from a profile
///
/// Emits `hl.monitor`, `hl.workspace_rule`, and `hl.bind` calls for Hyprland 0.55+.
/// Loaded from `hyprland.lua` via `pcall(require, "monitors")`.
pub fn generate_config(profile: &Profile) -> String {
    let mut lines = vec![format!(
        "-- Generated by hyprpier from profile: {}",
        profile.name
    )];
    lines.push(format!(
        "-- {}",
        profile.description.as_deref().unwrap_or("No description")
    ));
    lines.push(String::new());

    // Monitor entries
    for monitor in &profile.monitors {
        if monitor.enabled {
            let mut fields = vec![
                format!("output = {}", lua_str(&monitor.name)),
                format!("mode = {}", lua_str(&monitor.mode)),
                format!(
                    "position = \"{}x{}\"",
                    monitor.position.x, monitor.position.y
                ),
                format!("scale = {}", lua_num(monitor.scale)),
            ];
            if monitor.transform != 0 {
                fields.push(format!("transform = {}", monitor.transform));
            }
            lines.push(format!("hl.monitor({{ {} }})", fields.join(", ")));
        } else {
            lines.push(format!(
                "hl.monitor({{ output = {}, disabled = true }})",
                lua_str(&monitor.name)
            ));
        }
    }

    if !profile.workspaces.is_empty() {
        lines.push(String::new());
        for ws in &profile.workspaces {
            let default_part = if ws.default { ", default = true" } else { "" };
            lines.push(format!(
                "hl.workspace_rule({{ workspace = {}, monitor = {}{} }})",
                ws.id,
                lua_str(&ws.monitor),
                default_part
            ));
        }
    }

    // Lid switch bindings
    if let Some(ref lid) = profile.lid_switch {
        if lid.enabled {
            lines.push(String::new());
            lines.push("-- Lid switch handling".to_string());
            lines.push(format!(
                "hl.bind(\"switch:on:Lid Switch\", hl.dsp.exec_cmd({}), {{ locked = true }})",
                lua_str(&format!(
                    "hyprctl keyword monitor \"{},{}\"",
                    lid.monitor, lid.on_close
                ))
            ));
            lines.push(format!(
                "hl.bind(\"switch:off:Lid Switch\", hl.dsp.exec_cmd({}), {{ locked = true }})",
                lua_str(&format!(
                    "hyprctl keyword monitor \"{},{}\"",
                    lid.monitor, lid.on_open
                ))
            ));
        }
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Format a value as a Lua double-quoted string with escapes for `\` and `"`.
fn lua_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Format a finite f64 for Lua, preserving fractional part (1.0 stays "1.0").
fn lua_num(n: f64) -> String {
    if !n.is_finite() {
        return "1.0".to_string();
    }
    if n.fract() == 0.0 {
        format!("{:.1}", n)
    } else {
        format!("{}", n)
    }
}

/// Write the config to ~/.config/hypr/monitors.lua
pub fn write_config(profile: &Profile) -> Result<()> {
    let config = generate_config(profile);
    let path = crate::config::hyprland_monitors_lua()?;

    // Ensure parent directory exists
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(&path, config)
        .with_context(|| format!("Failed to write {}", path.display()))?;

    Ok(())
}

/// Apply a single monitor configuration via hyprctl
pub fn apply_monitor(monitor: &Monitor) -> Result<()> {
    let cmd = if monitor.enabled {
        let base = format!(
            "{},{},{}x{},{}",
            monitor.name, monitor.mode, monitor.position.x, monitor.position.y, monitor.scale
        );
        if monitor.transform != 0 {
            format!("{},transform,{}", base, monitor.transform)
        } else {
            base
        }
    } else {
        format!("{},disable", monitor.name)
    };

    let output = hyprctl_command()
        .args(["keyword", "monitor", &cmd])
        .output()
        .context("Failed to run hyprctl")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("hyprctl failed: {}", stderr);
    }

    Ok(())
}

/// Move a workspace to a monitor
pub fn move_workspace(workspace_id: u8, monitor: &str) -> Result<()> {
    let output = hyprctl_command()
        .args([
            "dispatch",
            "moveworkspacetomonitor",
            &format!("{} {}", workspace_id, monitor),
        ])
        .output()
        .context("Failed to move workspace")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("Failed to move workspace: {}", stderr);
    }

    Ok(())
}

/// Apply all monitors from a profile at runtime
pub fn apply_runtime(profile: &Profile) -> Result<()> {
    if !is_running() {
        return Ok(());
    }

    // Apply monitors
    for monitor in &profile.monitors {
        apply_monitor(monitor)?;
    }

    // Wait for monitor changes to take effect
    thread::sleep(Duration::from_millis(MONITOR_APPLY_DELAY_MS));

    // Move existing workspaces to correct monitors
    for ws in &profile.workspaces {
        for attempt in 0..WORKSPACE_MOVE_MAX_RETRIES {
            match move_workspace(ws.id, &ws.monitor) {
                Ok(_) => break,
                Err(_) if attempt < WORKSPACE_MOVE_MAX_RETRIES - 1 => {
                    thread::sleep(Duration::from_millis(WORKSPACE_MOVE_RETRY_DELAY_MS));
                }
                Err(e) => {
                    eprintln!("Warning: Failed to move workspace {}: {}", ws.id, e);
                }
            }
        }
    }

    Ok(())
}

/// Sort monitors: external first, laptop display (eDP) last
pub fn sort_monitors(monitors: &mut [Monitor]) {
    monitors.sort_by(|a, b| {
        let a_is_edp = a.name.to_lowercase().starts_with("edp");
        let b_is_edp = b.name.to_lowercase().starts_with("edp");
        a_is_edp.cmp(&b_is_edp)
    });
}

/// Auto-arrange monitors left-to-right
pub fn arrange_monitors(monitors: &mut [Monitor]) {
    let mut x_offset = 0;
    for monitor in monitors.iter_mut() {
        if monitor.enabled {
            monitor.position.x = x_offset;
            monitor.position.y = 0;
            let (w, _) = monitor.logical_size();
            x_offset += w;
        }
    }
}

/// Fix y-gaps for stacked monitors by snapping to the nearest overlapping neighbor
///
/// Groups monitors into rows by horizontal adjacency (tiling x-ranges within a
/// similar y-band). For each row group below the top, snaps its minimum y to the
/// bottom edge of the best x-overlapping monitor above, preserving internal y-offsets.
pub fn fix_stacking_gaps(monitors: &mut [Monitor]) {
    let enabled: Vec<usize> = monitors
        .iter()
        .enumerate()
        .filter(|(_, m)| m.enabled)
        .map(|(i, _)| i)
        .collect();

    if enabled.len() <= 1 {
        return;
    }

    // Group into rows by horizontal adjacency:
    // Monitors that tile horizontally (touching/overlapping x-ranges)
    // within a similar y-band belong to the same row.
    let row_groups = group_into_rows(&monitors, &enabled);

    if row_groups.len() <= 1 {
        return;
    }

    // Sort row groups by their minimum y
    let mut sorted_groups = row_groups;
    sorted_groups.sort_by_key(|group| {
        group.iter().map(|&i| monitors[i].position.y).min().unwrap_or(0)
    });

    // For each row group below the first, snap to the bottom edge of the
    // best overlapping monitor/group above, preserving internal y-offsets
    for g in 1..sorted_groups.len() {
        let group = &sorted_groups[g];
        let group_min_y = group.iter().map(|&i| monitors[i].position.y).min().unwrap_or(0);

        // Find the group x-range
        let group_x_min = group.iter()
            .map(|&i| monitors[i].position.x)
            .min().unwrap_or(0);
        let group_x_max = group.iter()
            .map(|&i| {
                let (w, _) = monitors[i].logical_size();
                monitors[i].position.x + w
            })
            .max().unwrap_or(0);
        let group_w = group_x_max - group_x_min;

        // Find best overlap in any row above
        let above_indices: Vec<usize> = sorted_groups[..g].iter().flatten().copied().collect();
        if let Some(target_y) = best_overlap_edge(&monitors, &above_indices, group_x_min, group_w, true) {
            let dy = target_y - group_min_y;
            if dy != 0 {
                for &i in group {
                    monitors[i].position.y += dy;
                }
            }
        }
    }
}

/// Group monitors into rows by horizontal adjacency
/// Monitors whose x-ranges touch or overlap and are within the same y-band
/// are considered part of the same row
fn group_into_rows(monitors: &[Monitor], enabled: &[usize]) -> Vec<Vec<usize>> {
    if enabled.is_empty() {
        return Vec::new();
    }

    // Sort by y then x
    let mut sorted: Vec<usize> = enabled.to_vec();
    sorted.sort_by(|&a, &b| {
        monitors[a].position.y.cmp(&monitors[b].position.y)
            .then(monitors[a].position.x.cmp(&monitors[b].position.x))
    });

    let mut groups: Vec<Vec<usize>> = Vec::new();

    for &idx in &sorted {
        let my = monitors[idx].position.y;
        let mx = monitors[idx].position.x;
        let (mw, mh) = monitors[idx].logical_size();

        // Try to join an existing group where:
        // 1. Y-bands overlap (this monitor's y-range intersects the group's y-range)
        // 2. X-ranges touch (this monitor is horizontally adjacent to some group member)
        let mut joined = false;
        for group in &mut groups {
            let group_y_min = group.iter().map(|&i| monitors[i].position.y).min().unwrap_or(0);
            let group_y_max = group.iter()
                .map(|&i| monitors[i].position.y + monitors[i].logical_size().1)
                .max().unwrap_or(0);

            // Check y-band overlap
            let y_overlaps = my < group_y_max && (my + mh) > group_y_min;
            if !y_overlaps {
                continue;
            }

            // Check x-adjacency with any group member
            let x_adjacent = group.iter().any(|&i| {
                let (iw, _) = monitors[i].logical_size();
                let ix = monitors[i].position.x;
                // Touching or overlapping in x
                mx < (ix + iw) && (mx + mw) > ix
            });

            if x_adjacent {
                group.push(idx);
                joined = true;
                break;
            }
        }

        if !joined {
            groups.push(vec![idx]);
        }
    }

    groups
}

/// Find the edge (bottom or top) of the monitor with the most x-overlap
fn best_overlap_edge(monitors: &[Monitor], indices: &[usize], mx: i32, mw: i32, bottom: bool) -> Option<i32> {
    let mut best_overlap = 0;
    let mut best_edge = None;
    for &j in indices {
        let (jw, jh) = monitors[j].logical_size();
        let jx = monitors[j].position.x;
        let jy = monitors[j].position.y;
        let overlap = (mx + mw).min(jx + jw) - mx.max(jx);
        if overlap > best_overlap {
            best_overlap = overlap;
            best_edge = Some(if bottom { jy + jh } else { jy });
        }
    }
    best_edge
}

/// Generate default workspaces for monitors
pub fn generate_workspaces(monitors: &[Monitor]) -> Vec<Workspace> {
    let mut workspaces = Vec::new();
    let mut ws_id: u8 = 1;

    let enabled_monitors: Vec<_> = monitors.iter().filter(|m| m.enabled).collect();
    let count = enabled_monitors.len();

    for monitor in enabled_monitors.iter() {
        // Distribute workspaces: 5 each for multi-monitor, 10 for single monitor
        let ws_count = if count > 1 { 5 } else { 10 };

        for j in 0..ws_count {
            if ws_id > 10 {
                break;
            }
            workspaces.push(Workspace {
                id: ws_id,
                monitor: monitor.name.clone(),
                default: j == 0, // First workspace on each monitor is default
            });
            ws_id += 1;
        }
    }

    workspaces
}

/// Generate default lid switch config for laptop display
pub fn generate_lid_switch(monitors: &[Monitor]) -> Option<LidSwitch> {
    // Find laptop display (eDP)
    let edp = monitors
        .iter()
        .find(|m| m.name.to_lowercase().starts_with("edp"))?;

    Some(LidSwitch {
        enabled: true,
        monitor: edp.name.clone(),
        on_close: "disable".to_string(),
        on_open: format!("{},0x0,1", edp.mode),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arrange_monitors_no_gaps_with_mixed_scales() {
        let mut monitors = vec![
            Monitor::test_fixture("DP-10", "3840x2160", 1.5, 0),
            Monitor::test_fixture("DP-11", "3840x2160", 1.5, 0),
            Monitor::test_fixture("DP-6", "1920x1080", 1.0, 3),
            Monitor::test_fixture("eDP-1", "1920x1200", 1.0, 0),
        ];
        arrange_monitors(&mut monitors);

        assert_eq!(monitors[0].position.x, 0);
        assert_eq!(monitors[1].position.x, 2560);
        assert_eq!(monitors[2].position.x, 5120);
        assert_eq!(monitors[3].position.x, 6200);

        for i in 1..monitors.len() {
            let (prev_w, _) = monitors[i - 1].logical_size();
            let expected = monitors[i - 1].position.x + prev_w;
            assert_eq!(
                monitors[i].position.x, expected,
                "gap between monitor {} and {}", i - 1, i
            );
        }
    }

    fn make_profile() -> Profile {
        Profile {
            name: "test".to_string(),
            description: Some("smoke".to_string()),
            monitors: vec![
                Monitor::test_fixture("eDP-1", "1920x1200", 1.0, 0),
                Monitor::test_fixture("DP-2", "3840x2160", 1.5, 1),
            ],
            workspaces: vec![
                Workspace { id: 1, monitor: "eDP-1".to_string(), default: true },
                Workspace { id: 2, monitor: "DP-2".to_string(), default: false },
            ],
            lid_switch: Some(LidSwitch {
                enabled: true,
                monitor: "eDP-1".to_string(),
                on_close: "disable".to_string(),
                on_open: "1920x1200@60,0x0,1".to_string(),
            }),
        }
    }

    #[test]
    fn generate_config_emits_lua_monitor_calls() {
        let p = make_profile();
        let out = generate_config(&p);
        assert!(out.contains("hl.monitor({ output = \"eDP-1\", mode = \"1920x1200@60\", position = \"0x0\", scale = 1.0 })"), "got:\n{}", out);
        assert!(out.contains("hl.monitor({ output = \"DP-2\", mode = \"3840x2160@60\", position = \"0x0\", scale = 1.5, transform = 1 })"), "got:\n{}", out);
    }

    #[test]
    fn generate_config_emits_disabled_monitor() {
        let mut p = make_profile();
        p.monitors[1].enabled = false;
        let out = generate_config(&p);
        assert!(out.contains("hl.monitor({ output = \"DP-2\", disabled = true })"), "got:\n{}", out);
    }

    #[test]
    fn generate_config_emits_workspace_rules() {
        let out = generate_config(&make_profile());
        assert!(out.contains("hl.workspace_rule({ workspace = 1, monitor = \"eDP-1\", default = true })"), "got:\n{}", out);
        assert!(out.contains("hl.workspace_rule({ workspace = 2, monitor = \"DP-2\" })"), "got:\n{}", out);
    }

    #[test]
    fn generate_config_emits_lid_binds() {
        let out = generate_config(&make_profile());
        assert!(
            out.contains("hl.bind(\"switch:on:Lid Switch\", hl.dsp.exec_cmd(\"hyprctl keyword monitor \\\"eDP-1,disable\\\"\"), { locked = true })"),
            "got:\n{}", out
        );
        assert!(
            out.contains("hl.bind(\"switch:off:Lid Switch\", hl.dsp.exec_cmd(\"hyprctl keyword monitor \\\"eDP-1,1920x1200@60,0x0,1\\\"\"), { locked = true })"),
            "got:\n{}", out
        );
    }

    #[test]
    fn generate_config_uses_lua_comment_header() {
        let out = generate_config(&make_profile());
        assert!(out.starts_with("-- Generated by hyprpier from profile: test\n-- smoke"), "got:\n{}", out);
    }

    #[test]
    fn arrange_monitors_unscaled_unchanged_behavior() {
        let mut monitors = vec![
            Monitor::test_fixture("eDP-1", "1920x1200", 1.0, 0),
            Monitor::test_fixture("DP-2", "1920x1080", 1.0, 0),
            Monitor::test_fixture("DP-6", "1920x1080", 1.0, 0),
        ];
        arrange_monitors(&mut monitors);
        assert_eq!(monitors[0].position.x, 0);
        assert_eq!(monitors[1].position.x, 1920);
        assert_eq!(monitors[2].position.x, 3840);
    }
}
